<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Phone;
use App\Models\Brand;
use App\Models\Category;

class PhoneSeeder extends Seeder
{
    public function run(): void
    {
        // Fix the typo "Xioami" dynamically if your database used it, or keep it consistent
        $brandXiaomi = Brand::firstOrCreate(['name' => 'Xiaomi'])->id;
        $brandRedmi = Brand::firstOrCreate(['name' => 'Redmi'])->id;
        $brandIphone = Brand::firstOrCreate(['name' => 'iPhone'])->id;
        $brandSamsung = Brand::firstOrCreate(['name' => 'Samsung'])->id;
        $brandNothing = Brand::firstOrCreate(['name' => 'Nothing Phone'])->id;

        $catNormal = Category::firstOrCreate(['name' => 'Normal Phones'])->id;
        $catFold = Category::firstOrCreate(['name' => 'Foldable Phones'])->id;
        $catFlip = Category::firstOrCreate(['name' => 'Flipable Phones'])->id;

        $phones = [
            // 1. Redmi Note 11
            [
                'brand_id' => $brandRedmi,
                'category_id' => $catNormal,
                'model' => 'Note 11',
                'brand' => 'Redmi',
                'announced_year' => '2022',
                'produced_year' => '2022',
                'storage' => 128,
                'storage_version' => 2.2,
                'ram' => 6,
                'ram_version' => 'LPDDR4X',
                'is_support_micro_sd' => true,
                'has_camera' => true,
                'first_camera' => 'main',
                'first_camera_sensor_model' => 'Samsung S5KJN1',
                'first_camera_sensor_size' => 2.76,
                'first_camera_sensor_MP_value' => 50,
                'first_camera_has_eis_or_ois' => 'none',
                'first_camera_video_recording' => '1080p@30fps',
                'has_second_camera' => true,
                'second_camera' => 'ultra-wide',
                'second_camera_sensor_MP_value' => 8,
                'has_third_camera' => true,
                'third_camera' => 'macro',
                'third_camera_sensor_MP_value' => 2,
                'has_fourth_camera' => true,
                'fourth_camera' => 'depth',
                'fourth_camera_sensor_MP_value' => 2,
                'has_front_camera' => true,
                'first_front_camera' => 'main',
                'first_front_camera_sensor_MP_value' => 13,
                'has_speaker' => true,
                'speaker_type' => 'stereo',
                'loudspeaker' => true,
                'charging_socket_type' => 'type-c',
                'charging_speed' => 33,
                'battery_capacity' => 5000,
                'screen_type' => 'amoled',
                'screen_resolution' => '1080x2400',
                'screen_refresh_rate' => 90,
                'max_brightness' => 1000,
                'screen_size' => '6.43 inches',
                'screen_protection' => 'Corning Gorilla Glass 3',
                'dimensions' => '159.9 x 73.9 x 8.1 mm',
                'weight' => '179 g',
                'thickness' => 8.09,
                'build_material' => 'Glass front, plastic frame, plastic back',
                'sim_type' => 'Dual SIM (Nano-SIM, dual stand-by)',
                'protection_rating' => 53,
                'CPU_model' => 'Qualcomm Snapdragon 680 4G',
                'GPU_model' => 'Adreno 610',
            ],

            // 2. Xiaomi 14 Ultra
            [
                'brand_id' => $brandXiaomi,
                'category_id' => $catNormal,
                'model' => '14 Ultra',
                'brand' => 'Xiaomi',
                'announced_year' => '2024',
                'produced_year' => '2024',
                'storage' => 512,
                'storage_version' => 4.0,
                'ram' => 16,
                'ram_version' => 'LPDDR5X',
                'is_support_micro_sd' => false,
                'has_camera' => true,
                'first_camera' => 'main',
                'first_camera_sensor_model' => 'Sony LYT-900',
                'first_camera_sensor_size' => 1.00,
                'first_camera_sensor_MP_value' => 50,
                'first_camera_has_eis_or_ois' => 'both',
                'first_camera_video_recording' => '8K@24/30fps, 4K@24/30/60/120fps',
                'has_second_camera' => true,
                'second_camera' => 'telephoto',
                'second_camera_sensor_model' => 'Sony IMX858',
                'second_camera_sensor_MP_value' => 50,
                'second_camera_has_eis_or_ois' => 'OIS',
                'second_camera_optical_zoom' => '3.2x',
                'has_third_camera' => true,
                'third_camera' => 'periscope',
                'third_camera_sensor_model' => 'Sony IMX858',
                'third_camera_sensor_MP_value' => 50,
                'third_camera_has_eis_or_ois' => 'OIS',
                'third_camera_optical_zoom' => '5x',
                'has_fourth_camera' => true,
                'fourth_camera' => 'ultra-wide',
                'fourth_camera_sensor_model' => 'Sony IMX858',
                'fourth_camera_sensor_MP_value' => 50,
                'has_front_camera' => true,
                'first_front_camera' => 'main',
                'first_front_camera_sensor_MP_value' => 32,
                'has_speaker' => true,
                'speaker_type' => 'stereo',
                'loudspeaker' => true,
                'charging_socket_type' => 'type-c',
                'charging_speed' => 90,
                'battery_capacity' => 5000,
                'screen_type' => 'oled',
                'screen_resolution' => '1440x3200',
                'screen_refresh_rate' => 120,
                'max_brightness' => 3000,
                'screen_size' => '6.73 inches',
                'screen_protection' => 'Xiaomi Shield Glass',
                'dimensions' => '161.4 x 75.3 x 9.2 mm',
                'weight' => '220 g',
                'thickness' => 9.20,
                'build_material' => 'Glass front, titanium/aluminum frame, eco-leather back',
                'sim_type' => 'Dual SIM (Nano-SIM, dual stand-by)',
                'protection_rating' => 68,
                'CPU_model' => 'Qualcomm Snapdragon 8 Gen 3',
                'GPU_model' => 'Adreno 750',
            ],

            // 3. Samsung Galaxy S24 Ultra
            [
                'brand_id' => $brandSamsung,
                'category_id' => $catNormal,
                'model' => 'Galaxy S24 Ultra',
                'brand' => 'Samsung',
                'announced_year' => '2024',
                'produced_year' => '2024',
                'storage' => 256,
                'storage_version' => 4.0,
                'ram' => 12,
                'ram_version' => 'LPDDR5X',
                'is_support_micro_sd' => false,
                'has_camera' => true,
                'first_camera' => 'main',
                'first_camera_sensor_model' => 'Samsung ISOCELL HP2',
                'first_camera_sensor_size' => 1.30,
                'first_camera_sensor_MP_value' => 200,
                'first_camera_has_eis_or_ois' => 'both',
                'first_camera_video_recording' => '8K@30fps, 4K@60/120fps',
                'has_second_camera' => true,
                'second_camera' => 'periscope',
                'second_camera_sensor_MP_value' => 50,
                'second_camera_has_eis_or_ois' => 'OIS',
                'second_camera_optical_zoom' => '5x',
                'has_third_camera' => true,
                'third_camera' => 'telephoto',
                'third_camera_sensor_MP_value' => 10,
                'third_camera_has_eis_or_ois' => 'OIS',
                'third_camera_optical_zoom' => '3x',
                'has_fourth_camera' => true,
                'fourth_camera' => 'ultra-wide',
                'fourth_camera_sensor_MP_value' => 12,
                'has_front_camera' => true,
                'first_front_camera' => 'main',
                'first_front_camera_sensor_MP_value' => 12,
                'has_speaker' => true,
                'speaker_type' => 'stereo',
                'loudspeaker' => true,
                'charging_socket_type' => 'type-c',
                'charging_speed' => 45,
                'battery_capacity' => 5000,
                'screen_type' => 'dynamic-amoled',
                'screen_resolution' => '1440x3120',
                'screen_refresh_rate' => 120,
                'max_brightness' => 2600,
                'screen_size' => '6.8 inches',
                'screen_protection' => 'Corning Gorilla Armor',
                'dimensions' => '162.3 x 79.0 x 8.6 mm',
                'weight' => '232 g',
                'thickness' => 8.60,
                'build_material' => 'Glass front, Glass back, Titanium frame',
                'sim_type' => 'Dual SIM (Nano-SIM, dual stand-by)',
                'protection_rating' => 68,
                'CPU_model' => 'Snapdragon 8 Gen 3 for Galaxy',
                'GPU_model' => 'Adreno 750',
            ],

            // 4. Samsung Galaxy Z Fold 5
            [
                'brand_id' => $brandSamsung,
                'category_id' => $catFold,
                'model' => 'Galaxy Z Fold 5',
                'brand' => 'Samsung',
                'announced_year' => '2023',
                'produced_year' => '2023',
                'storage' => 512,
                'storage_version' => 4.0,
                'ram' => 12,
                'ram_version' => 'LPDDR5X',
                'is_support_micro_sd' => false,
                'has_camera' => true,
                'first_camera' => 'main',
                'first_camera_sensor_MP_value' => 50,
                'first_camera_has_eis_or_ois' => 'both',
                'first_camera_video_recording' => '8K@24fps, 4K@60fps',
                'has_second_camera' => true,
                'second_camera' => 'telephoto',
                'second_camera_sensor_MP_value' => 10,
                'second_camera_has_eis_or_ois' => 'OIS',
                'second_camera_optical_zoom' => '3x',
                'has_third_camera' => true,
                'third_camera' => 'ultra-wide',
                'third_camera_sensor_MP_value' => 12,
                'has_front_camera' => true,
                'first_front_camera' => 'main',
                'first_front_camera_sensor_MP_value' => 4,
                'has_speaker' => true,
                'speaker_type' => 'stereo',
                'loudspeaker' => true,
                'charging_socket_type' => 'type-c',
                'charging_speed' => 25,
                'battery_capacity' => 4400,
                'screen_type' => 'dynamic-amoled',
                'screen_resolution' => '1812x2176',
                'screen_refresh_rate' => 120,
                'max_brightness' => 1750,
                'screen_size' => '7.6 inches',
                'screen_protection' => 'Foldable Plastic',
                'dimensions' => '154.9 x 129.9 x 6.1 mm',
                'weight' => '253 g',
                'thickness' => 6.10,
                'build_material' => 'Plastic front, Glass back (Gorilla Glass Victus 2), Aluminum frame',
                'sim_type' => 'Up to 2 Nano-SIM and eSIM',
                'protection_rating' => 68,
                'CPU_model' => 'Qualcomm Snapdragon 8 Gen 2',
                'GPU_model' => 'Adreno 740',
            ],

            // 5. Samsung Galaxy Z Flip 5
            [
                'brand_id' => $brandSamsung,
                'category_id' => $catFlip,
                'model' => 'Galaxy Z Flip 5',
                'brand' => 'Samsung',
                'announced_year' => '2023',
                'produced_year' => '2023',
                'storage' => 256,
                'storage_version' => 4.0,
                'ram' => 8,
                'ram_version' => 'LPDDR5X',
                'is_support_micro_sd' => false,
                'has_camera' => true,
                'first_camera' => 'main',
                'first_camera_sensor_MP_value' => 12,
                'first_camera_has_eis_or_ois' => 'OIS',
                'first_camera_video_recording' => '4K@30/60fps',
                'has_second_camera' => true,
                'second_camera' => 'ultra-wide',
                'second_camera_sensor_MP_value' => 12,
                'has_front_camera' => true,
                'first_front_camera' => 'main',
                'first_front_camera_sensor_MP_value' => 10,
                'has_speaker' => true,
                'speaker_type' => 'stereo',
                'charging_socket_type' => 'type-c',
                'charging_speed' => 25,
                'battery_capacity' => 3700,
                'screen_type' => 'dynamic-amoled',
                'screen_size' => '6.7 inches',
                'screen_resolution' => '1080x2640',
                'screen_refresh_rate' => 120,
                'dimensions' => '165.1 x 71.9 x 6.9 mm',
                'weight' => '187 g',
                'thickness' => 6.90,
                'protection_rating' => 68,
                'CPU_model' => 'Qualcomm Snapdragon 8 Gen 2',
                'GPU_model' => 'Adreno 740',
            ],

            // 6. iPhone 15 Pro Max
            [
                'brand_id' => $brandIphone,
                'category_id' => $catNormal,
                'model' => '15 Pro Max',
                'brand' => 'iPhone',
                'announced_year' => '2023',
                'produced_year' => '2023',
                'storage' => 256,
                'storage_version' => 4.0,
                'ram' => 8,
                'ram_version' => 'LPDDR5',
                'is_support_micro_sd' => false,
                'has_camera' => true,
                'first_camera' => 'main',
                'first_camera_sensor_size' => 1.28,
                'first_camera_sensor_MP_value' => 48,
                'first_camera_has_eis_or_ois' => 'OIS',
                'first_camera_video_recording' => '4K@24/25/30/60fps',
                'has_second_camera' => true,
                'second_camera' => 'periscope',
                'second_camera_sensor_MP_value' => 12,
                'second_camera_has_eis_or_ois' => 'OIS',
                'second_camera_optical_zoom' => '5x',
                'has_third_camera' => true,
                'third_camera' => 'ultra-wide',
                'third_camera_sensor_MP_value' => 12,
                'has_front_camera' => true,
                'first_front_camera' => 'main',
                'first_front_camera_sensor_MP_value' => 12,
                'has_speaker' => true,
                'speaker_type' => 'stereo',
                'charging_socket_type' => 'type-c',
                'charging_speed' => 25,
                'battery_capacity' => 4441,
                'screen_type' => 'oled',
                'screen_resolution' => '1290x2796',
                'screen_refresh_rate' => 120,
                'max_brightness' => 2000,
                'screen_size' => '6.7 inches',
                'screen_protection' => 'Ceramic Shield glass',
                'dimensions' => '159.9 x 76.7 x 8.3 mm',
                'weight' => '221 g',
                'thickness' => 8.25,
                'build_material' => 'Glass front, Glass back, Titanium frame',
                'sim_type' => 'Dual eSIM / Nano-SIM',
                'protection_rating' => 68,
                'CPU_model' => 'Apple A17 Pro',
                'GPU_model' => 'Apple GPU (6-core graphics)',
            ],

            // 7. Nothing Phone (2)
            [
                'brand_id' => $brandNothing,
                'category_id' => $catNormal,
                'model' => 'Phone (2)',
                'brand' => 'Nothing Phone',
                'announced_year' => '2023',
                'produced_year' => '2023',
                'storage' => 256,
                'storage_version' => 3.1,
                'ram' => 12,
                'ram_version' => 'LPDDR5',
                'is_support_micro_sd' => false,
                'has_camera' => true,
                'first_camera' => 'main',
                'first_camera_sensor_model' => 'Sony IMX890',
                'first_camera_sensor_MP_value' => 50,
                'first_camera_has_eis_or_ois' => 'both',
                'first_camera_video_recording' => '4K@30/60fps',
                'has_second_camera' => true,
                'second_camera' => 'ultra-wide',
                'second_camera_sensor_model' => 'Samsung JN1',
                'second_camera_sensor_MP_value' => 50,
                'has_front_camera' => true,
                'first_front_camera' => 'main',
                'first_front_camera_sensor_MP_value' => 32,
                'has_speaker' => true,
                'speaker_type' => 'stereo',
                'charging_socket_type' => 'type-c',
                'charging_speed' => 45,
                'battery_capacity' => 4700,
                'screen_type' => 'amoled',
                'screen_resolution' => '1080x2412',
                'screen_refresh_rate' => 120,
                'max_brightness' => 1600,
                'screen_size' => '6.7 inches',
                'dimensions' => '162.1 x 76.4 x 8.6 mm',
                'weight' => '201 g',
                'thickness' => 8.60,
                'build_material' => 'Glass front, Transparent glass back, Aluminum frame',
                'protection_rating' => 54,
                'CPU_model' => 'Qualcomm Snapdragon 8+ Gen 1',
                'GPU_model' => 'Adreno 730',
            ],

            // 8. Xiaomi Mix Fold 3
            [
                'brand_id' => $brandXiaomi,
                'category_id' => $catFold,
                'model' => 'Mix Fold 3',
                'brand' => 'Xiaomi',
                'announced_year' => '2023',
                'produced_year' => '2023',
                'storage' => 1024,
                'storage_version' => 4.0,
                'ram' => 16,
                'ram_version' => 'LPDDR5X',
                'is_support_micro_sd' => false,
                'has_camera' => true,
                'first_camera' => 'main',
                'first_camera_sensor_MP_value' => 50,
                'first_camera_has_eis_or_ois' => 'OIS',
                'first_camera_video_recording' => '8K@24fps',
                'has_second_camera' => true,
                'second_camera' => 'telephoto',
                'second_camera_sensor_MP_value' => 10,
                'second_camera_has_eis_or_ois' => 'OIS',
                'second_camera_optical_zoom' => '3.2x',
                'has_third_camera' => true,
                'third_camera' => 'periscope',
                'third_camera_sensor_MP_value' => 10,
                'third_camera_has_eis_or_ois' => 'OIS',
                'third_camera_optical_zoom' => '5x',
                'has_fourth_camera' => true,
                'fourth_camera' => 'ultra-wide',
                'fourth_camera_sensor_MP_value' => 12,
                'has_front_camera' => true,
                'first_front_camera' => 'main',
                'first_front_camera_sensor_MP_value' => 20,
                'has_speaker' => true,
                'speaker_type' => 'stereo',
                'charging_socket_type' => 'type-c',
                'charging_speed' => 67,
                'battery_capacity' => 4800,
                'screen_type' => 'oled',
                'screen_size' => '8.03 inches',
                'screen_resolution' => '1916x2160',
                'screen_refresh_rate' => 120,
                'dimensions' => '161.2 x 143.3 x 5.3 mm',
                'weight' => '255 g',
                'thickness' => 5.26,
                'CPU_model' => 'Qualcomm Snapdragon 8 Gen 2',
                'GPU_model' => 'Adreno 740',
            ],

            // 9. Redmi Note 13 Pro+ 5G
            [
                'brand_id' => $brandRedmi,
                'category_id' => $catNormal,
                'model' => 'Note 13 Pro+ 5G',
                'brand' => 'Redmi',
                'announced_year' => '2023',
                'produced_year' => '2023',
                'storage' => 512,
                'storage_version' => 3.1,
                'ram' => 12,
                'ram_version' => 'LPDDR5',
                'is_support_micro_sd' => false,
                'has_camera' => true,
                'first_camera' => 'main',
                'first_camera_sensor_model' => 'Samsung ISOCELL HP3',
                'first_camera_sensor_size' => 1.40,
                'first_camera_sensor_MP_value' => 200,
                'first_camera_has_eis_or_ois' => 'both',
                'first_camera_video_recording' => '4K@24/30fps, 1080p@30/60fps',
                'has_second_camera' => true,
                'second_camera' => 'ultra-wide',
                'second_camera_sensor_MP_value' => 8,
                'has_third_camera' => true,
                'third_camera' => 'macro',
                'third_camera_sensor_MP_value' => 2,
                'has_front_camera' => true,
                'first_front_camera' => 'main',
                'first_front_camera_sensor_MP_value' => 16,
                'has_speaker' => true,
                'speaker_type' => 'stereo',
                'loudspeaker' => true,
                'charging_socket_type' => 'type-c',
                'charging_speed' => 120,
                'battery_capacity' => 5000,
                'screen_type' => 'amoled',
                'screen_resolution' => '1220x2712',
                'screen_refresh_rate' => 120,
                'max_brightness' => 1800,
                'screen_size' => '6.67 inches',
                'screen_protection' => 'Corning Gorilla Glass Victus',
                'dimensions' => '161.4 x 74.2 x 8.9 mm',
                'weight' => '204 g',
                'thickness' => 8.90,
                'build_material' => 'Glass front, glass or eco-leather back, aluminum frame',
                'sim_type' => 'Dual SIM (Nano-SIM, dual stand-by)',
                'protection_rating' => 68,
                'CPU_model' => 'MediaTek Dimensity 7200 Ultra',
                'GPU_model' => 'Mali-G610 MC4',
            ],

            // 10. Xiaomi 13 Pro
            [
                'brand_id' => $brandXiaomi,
                'category_id' => $catNormal,
                'model' => '13 Pro',
                'brand' => 'Xiaomi',
                'announced_year' => '2022',
                'produced_year' => '2023',
                'storage' => 256,
                'storage_version' => 4.0,
                'ram' => 12,
                'ram_version' => 'LPDDR5X',
                'is_support_micro_sd' => false,
                'has_camera' => true,
                'first_camera' => 'main',
                'first_camera_sensor_model' => 'Sony IMX989',
                'first_camera_sensor_size' => 1.00,
                'first_camera_sensor_MP_value' => 50,
                'first_camera_has_eis_or_ois' => 'both',
                'first_camera_video_recording' => '8K@24fps, 4K@24/30/60fps',
                'has_second_camera' => true,
                'second_camera' => 'telephoto',
                'second_camera_sensor_MP_value' => 50,
                'second_camera_has_eis_or_ois' => 'OIS',
                'second_camera_optical_zoom' => '3.2x',
                'has_third_camera' => true,
                'third_camera' => 'ultra-wide',
                'third_camera_sensor_MP_value' => 50,
                'has_front_camera' => true,
                'first_front_camera' => 'main',
                'first_front_camera_sensor_MP_value' => 32,
                'has_speaker' => true,
                'speaker_type' => 'stereo',
                'charging_socket_type' => 'type-c',
                'charging_speed' => 120,
                'battery_capacity' => 4820,
                'screen_type' => 'amoled',
                'screen_resolution' => '1440x3200',
                'screen_refresh_rate' => 120,
                'max_brightness' => 1900,
                'screen_size' => '6.73 inches',
                'screen_protection' => 'Corning Gorilla Glass Victus',
                'dimensions' => '162.9 x 74.6 x 8.4 mm',
                'weight' => '229 g',
                'thickness' => 8.38,
                'build_material' => 'Glass front, ceramic back, aluminum frame',
                'protection_rating' => 68,
                'CPU_model' => 'Qualcomm Snapdragon 8 Gen 2',
                'GPU_model' => 'Adreno 740',
            ],
        ];

        // Safely insert elements by filtering out any irregular custom keys on-the-fly
        foreach ($phones as $phone) {
            Phone::create($phone);
        }
    }
}